from parse_hh_data import download, parse
import re


def digit_or_en_latter(s):
    return all(c in "0123456789 abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ./" for c in s)


list_skills = []
resume_ids = download.resume_ids("1", "1.221", 1, 10)
for id in resume_ids:
    resume = download.resume(id)
    resume = parse.resume(resume)
    for skill in resume['skill_set']:
        if skill not in list_skills and digit_or_en_latter(skill):
            list_skills.append(skill)
print(list_skills)
list_skills_final = ['Python', 'Oracle Pl/SQL', 'PyQt5', 'Delphi', 'Oracle 11G', 'Atlassian Jira', 'Cadence',
                    'Calibre work bench', 'Linux', 'MS Word', 'MS Excel', 'MS PowerPoint', 'Unigraphics NX', 'MS SQL',
                    'HP Loadrunner', 'Telegraph', 'Grafana', 'InfluxDB', 'Performance Center', 'CSS', 'HTML', 'Java',
                    'JavaScript', 'jQuery', 'MySQL', 'PHP', 'Git', 'Symfony', 'MongoDB', 'HTML5', 'Ubuntu Server',
                    'Debian', 'Bootstrap', 'Apache HTTP Server', 'SQL', 'Golang', 'Joomla CMS', 'AutoCAD', 'Web Design',
                    'CSS3', 'NetBeans', 'GitLab', 'Figma', 'CakePHP', 'CMS Wordpress', 'Virtuemart', 'NetCat',
                    'JSON API', 'Less', 'Sass', 'Gulp', 'Ajax', 'XML', 'Adobe Photoshop', 'Usability', 'Test case',
                    'Selenium', 'Jenkins', 'postman', 'Wireshark', 'apache jmeter', 'testlink', 'xmind', 'API', 'JSON',
                    'pixel perfect', 'TypeScript', 'React', 'Firebase', 'Fastlane', 'BABEL', 'WebPack', 'NEXTJS',
                    'Python1', 'Linux1', 'Django Framework1', 'Aiohttp1', 'API1', 'Redis1', 'Docker1', 'PostgreSQL1',
                    'MongoDB1', 'Golang1', 'Git1', 'asyncio1', 'Backend1', 'FastAPI1', 'Kafka1', 'Xcode', 'Swift',
                    'SwiftUI', 'iOS', 'UX', 'UI', 'Agile', 'Scrum', 'VMware', 'TeamViewer', 'WPF', 'Adobe Premier Pro',
                    'Adobe Audition', 'MS Dynamics NAV', 'Python jun', 'ARIS', 'MS Visio', 'Atlassian Confluence',
                    'CorelDRAW', 'Adobe Illustrator', 'SAP', 'CRM', 'ERP', 'Bash', 'Jupyter Notebook', 'Java script',
                    'Google apps script', 'Google Docs', 'Google sheets', 'Boolean search',
                    'Business Intelligence Systems', 'MS Project', 'Windows API', 'Data Mining', 'UML', 'Data Analysis',
                    'MS Access', 'AutoIT', 'UIpath', 'OLTP/ETL/DWH/MDX/OLAP', 'VBA/VBScript', 'REST API',
                    'Azure/Power Apps/Power Automation', 'MATLAB', 'MS Office', 'PROTEUS ISIS ARES', 'Mathcad', 'Qt',
                    'Astra Linux', 'PostgreSQL', 'Android Studio', 'Android SDK', 'Ubuntu', 'SolidWorks', 'Android',
                    'Docker', 'GitLab CI', 'Rust', 'Kotlin', 'NixOS', 'Coq', 'STM32', 'Flutter', 'FreeCAD',
                    'Research And Development', 'Wireguard', 'ESP8266', 'Polymer', 'ORACLE', 'Webpack', 'Node.js',
                    'Redux', 'REST', 'SPA', 'FIGMA', 'Axure RP', 'Intellij IDEA', 'MS Visual Studio', 'AngularJS',
                    'MS SharePoint', 'ReactJS', 'BPMN', 'ML', 'NumPy', 'Pandas', 'SciPy', 'Matplotlib', 'LightGBM',
                    'CatBoost', 'XGBoost', 'Spark', 'Keras', 'Machine learning', 'TensorFlow', 'Power BI', 'Vue',
                    'Vuetify', 'SCSS', 'Axios', 'Vuex', 'Vuelidate', 'Nuxt', 'Quasar', 'Pug', 'Numpy', 'Vkontakte Api',
                    'LabVIEW', 'PyTorch', 'MS SQL Server', 'MVC', 'Wordpress', 'Windows Server 2012', '.NET Framework',
                    'ASP.NET', 'TFC', 'Azure', 'ReSharper', 'Nunit3', 'Nunit2', 'Json', 'XPath', 'Regex', 'LINQ',
                    'GitHub', 'Entity Framework', 'PHP5', 'SEO', 'Js', 'DOMObject', 'react', 'React Js', 'JPA', 'JDBC',
                    'Hibernate ORM', 'Spring Framework', 'Spring Boot', 'Spring Data', 'Spring MVC', 'Apache Maven',
                    'Apache Tomcat', 'Mac Os', 'React js', 'WebSockets', 'PHPUnit', 'Laravel', 'Yii2', 'Nginx',
                    'Machine Learning', 'Deep Learning', 'ELK', 'C', 'NATS', 'Protobuf', 'concurrency', 'Prometheus',
                    'SWIFT', 'Sketch', 'CoreData', 'Scss', 'React.js', 'jest/enzyme', 'Jupiter Notebook', 'Seaborn',
                    'EDA', 'Visual Basic', 'MS Visual Basic', 'QuarkXPress', 'Blender 3D', 'Unity', 'PowerShell',
                    'Windows Server', 'Cisco', 'MS Exchange', 'Active Directory', 'phpMyAdmin', 'PHP4',
                    'Microsoft Access', 'typo3', 'VBA', 'Vue.js', 'SCADA', 'ePLAN', 'webpack', 'figma', 'HAML', 'Ruby',
                    '960 grid', 'HTML51', 'CSS31', 'JavaScript1', 'VueJS1', 'Nuxt.js1', 'Webpack1', 'Node.js1',
                    'SAP SD', 'SAP MM', 'SAP ERP', 'SAP Project', 'SAP BW', 'SAP FI', 'SAP LO', 'SPRo', 'SAP HANA',
                    'Project management', 'Sales Skills', 'Product Marketing', 'Zeplin', 'Frontend', 'Pixel Perfecf',
                    'ES6', 'Material UI', 'Strapi', 'iOS SDK', 'Realm', 'Core Data', 'AutoLayout', 'Delegate',
                    'URLSession', 'Thread', 'CALayer', 'MVVM', 'OpenOffice', 'ERP Systems', 'Adobe Acrobat',
                    'Windows 7', 'SmartPlant', 'Blockchain', 'Solidity', 'Code review', 'Design Patterns', 'OOP', 'TDD',
                    'Spring', 'Trading', 'LLVM', 'Hyperledger Fabric', 'Corda', 'Fintech',
                    'Quantum physics and biology', 'Math skills', 'Go', 'Cloud Solutions', 'Adobe CS',
                    'Convolutional Neural Networks', 'Neural Network', 'Pretrained NN', 'Django Framework', 'Big Data',
                    'py', 'SSMS', 'DBeaver', 'PL/pgSQL', 'NoSQL', 'BASIC', 'Postgre', 'MapReduce', 'Google Analytics',
                    'Power Pivot', 'QlikSense', 'Time management', 'MIKROTIK', 'TCP/IP', 'Zabbix', 'Visual Studio Code',
                    'CSS1', 'HTML1', 'Ajax1', 'React1', 'Redux1', 'Express js1', 'Adobe Photoshop1', 'Bootstrap1',
                    'REST1', 'Mongoose1', 'Handlebars1', 'FireBase1', 'Jasmine1', 'Readymag1', 'SOLID', 'JavaSE',
                    'Maven', 'Html/Css/Less', 'RabbitMQ', 'Microservices architecture', 'Postgres', 'Gitlab', 'QML',
                    'Proteus', 'UE4', 'UIKit', 'Alamofire', 'SwiftyJSON', 'GCD', 'FireBase', 'NSOperation', 'SOAP',
                    'MobX1', 'Less1', 'React Hooks', 'Redux Forms', 'MobX', 'Webextension', 'Typescript', 'Jest',
                    'PostCSS', 'DOM API', 'Hyperledger', 'Databases', 'Investments', 'Algorithms', 'Data Structers',
                    'x86/ARM assembly', 'Latex', 'Mathematical Analysis', 'ClickHouse', 'HDFS',
                    'Agile Project Management', 'YouTrack', 'XML/Xslt', 'Postman', 'FastReport', 'Atlassian Trello',
                    'Basecamp', 'Windows 8', 'Windows Xp', 'Internet', 'RxJava/RxAndroid', 'Test Driven Development',
                    'Google Play Services', 'QA', 'CI/CD', 'Material Design', 'Espresso and Dagger',
                    'SQL XML JSON RESTful API', 'Fragment Adapters Tabhost ViewPager Push notifications',
                    'MS Visual FoxPro', 'Embarcadero Delphi', 'Svg', 'Bootstrap 4', 'Data Science', 'Scipy',
                    'ML models', 'Plotly', 'BeautifulSoup', 'Sklearn', 'NLTK', 'TOC', 'PMBOK',
                    'Business Continuity Management', 'Unix', 'MS Outlook', 'SQL Server', 'JSX', 'Nuxt.js', 'SQL1',
                    'MySQL1', 'Windows Forms', '.NET Core', 'ASP.NET MVC', 'Java1', 'Android1',
                    'Microsoft Visual Studio', 'Android Studio1', 'Spring Security', 'Trello', 'Slack', 'Gradle',
                    'Redis', 'OpenCl', 'ZedSDK', 'Cocoa', 'uiKit', 'clickhouse DB', 'Active MQ', 'BPM', 'Router5',
                    'Github', 'ADO.NET', 'Unit Testing', 'SVN', 'TFS', 'Avaya Call Management Systems', 'GPON FTTh',
                    'FreePBX', 'Mikrotik', 'E1 PRI', 'PBX', 'IPKVM', 'Penetration Testing Kali Linux', 'Cisco Catalyst',
                    'SIP/H.323', 'EPON', 'DocsVision', 'Borland Delphi', 'PDM', 'CSS4', 'HTML4', 'JavaScript4', 'Git4',
                    'jQuery4', 'iOS1', 'Xcode1', 'UIKit1', 'AutoLayout1', 'Design Patterns1', 'GCD1', 'CocoaPods1',
                    'Rest API1', 'URLSession1', 'CoreLocation1', 'Realm1', 'ARC1', 'Swift1', 'Interface Builder1',
                    'GitHub1', 'Kingfisher1', 'MapKit1', 'MVC1', 'Sketch1', 'SOLID1', 'Mac Os1', 'AVPlayer1',
                    'Firebase1', 'CoreData1', 'clean swift', 'Unreal engine', 'Autodesk Maya', 'Blueprint scripting',
                    'github', 'NPM', 'ESLint', 'Erlang', 'Blazor Server App', 'Vuejs', 'Npm', 'sklearn', 'Snakemake',
                    'Java Syntax', 'Java Core', 'Collections', 'Multithreading', 'SQLite', 'Room database',
                    'Retrofit 2', 'Dagger Hilt', 'Glide', 'Jetpack Components', 'ABAP', 'ALV grid', 'SAP PM', 'SAP eWM',
                    'FoxPro', 'WebSocket', 'ReactNative', 'SIMENS', 'Valmet', 'Metso', 'Yokogawa', 'AllenBradley',
                    'TIA Portal', 'Mac Os X Server', 'Software Development', 'Object Pascal/Delphi', 'UWP',
                    'Pixel Perfect', 'Avacode', 'Waterfall', 'Marmoset', '3D Max', 'Web Application Development',
                    'Redmine', 'Business Planning', 'PMI', 'ITIL', 'ITSM', 'SAP TM', 'golang', 'Game Programming',
                    'Java SE', 'Apache Kafka', 'Liquibase', 'Kubernetes', 'GC', 'JUnit', 'Unix Shell Scripts',
                    'Windows', 'Excel', 'Digital Signal Processing', 'Computer Science', 'Analytics', 'Data Engineer',
                    'Artificial Intelligence', 'Neural Networks', 'Tableau', 'Jeager', 'Grpc', 'ansible', 'react.js',
                    'redux', 'vue.js', 'vue', 'HTTP', 'typescript', 'ES5', 'express', 'Flask', 'FastAPI', 'SQLAlchemy',
                    'CURL', 'pgAdmin', 'Celery', 'JWT', 'PyTest', 'Flexbox', 'Eclipse', 'SQA', 'Testing Framework',
                    'AVR', 'MSP', 'Software', 'DSP', 'lwIP', 'Ethernet', 'IoT', 'UDP', 'Wifi networks', 'Radio',
                    'zigbee', 'ISM', 'Java Servlets', 'Java EE', 'JSP', 'ORM', 'EclipseLink', 'Django Rest Framework',
                    'Memcached', 'AXAPTA', 'MS Dynamics AX', 'ms Dynamics AX 2012', 'Sony Vegas', 'Adobe Premier',
                    'Huawei', 'Django rest framework', 'Yii', '3ds Max', 'ZBrush', 'Simulink', 'COMSOL Multiphysics',
                    'Arduino', 'Global Navigation Satellite System', 'scratch', 'phaser 3', 'Wolfram Matematica',
                    'React JS', 'GraphQL', 'Angular', 'Oracle Spatial', 'ArcGIS', 'AutoCAD Map 3D', 'QGIS', 'FME',
                    'Cesium', 'MapGuide Maestro', 'Threejs', 'Photomod', 'JSTL', 'HSQLDB', 'Oracle Database', 'JAXB',
                    'StaX', 'ehcache', 'Elasticsearch', 'babel', 'node', 'npm', 'expressJs', 'Tkinter', 'AstraLinux',
                    'SAP BI', 'SAP BPC', 'SCSS/LESS', 'Perl', 'SOAP UI', 'WSDL', 'Swagger', 'DocBook', 'Drakon',
                    'Spyne', 'ESIA', 'Xsd', 'stylus', 'pug', 'jquery api', 'css 3', 'bitrix', 'Mercurial']
